### ISSUE TITLE
Match the name length of the dest station type

### ISSUE THREAD

**Issue by GaHong3400** [railmapgen/rmp#654]
我已嘗試重新整理或重新上載設定檔，但依然顯示錯誤
以下是詳細資料

TypeError: Cannot read properties of undefined (reading 'split')

    at ka (https://railmapgen.github.io/rmp/assets/stations-SXCuavby.js:1:90550)
    at Re (https://railmapgen.github.io/rmp/assets/svg-wrapper-3UkPnlrR.js:1:6471)
    at svg
    at He (https://railmapgen.github.io/rmp/assets/svg-wrapper-3UkPnlrR.js:1:10030)
    at div
    at https://railmapgen.github.io/rmp/assets/chakra-sjIlidOs.js:16:6180
    at https://railmapgen.github.io/rmp/assets/chakra-sjIlidOs.js:16:134399
    at https://railmapgen.github.io/rmp/assets/chakra-sjIlidOs.js:16:315324
    at e (https://railmapgen.github.io/rmp/assets/index-UvyvJ3eL.js:9:71891)
    at Suspense
    at div
    at https://railmapgen.github.io/rmp/assets/chakra-sjIlidOs.js:16:6180
    at https://railmapgen.github.io/rmp/assets/chakra-sjIlidOs.js:16:134399
    at https://railmapgen.github.io/rmp/assets/chakra-sjIlidOs.js:16:315324
    at Ug (https://railmapgen.github.io/rmp/assets/index-UvyvJ3eL.js:9:79439)
    at vm (https://railmapgen.github.io/rmp/assets/index-UvyvJ3eL.js:9:90598)
    at Kp (https://railmapgen.github.io/rmp/assets/chakra-sjIlidOs.js:16:135749)
    at dp (https://railmapgen.github.io/rmp/assets/chakra-sjIlidOs.js:16:17554)
    at y0 (https://railmapgen.github.io/rmp/assets/chakra-sjIlidOs.js:16:6400)
    at uT (https://railmapgen.github.io/rmp/assets/chakra-sjIlidOs.js:16:135070)
    at hT (https://railmapgen.github.io/rmp/assets/chakra-sjIlidOs.js:16:136197)
    at https://railmapgen.github.io/rmp/assets/chakra-sjIlidOs.js:16:249460
    at bm (https://railmapgen.github.io/rmp/assets/index-UvyvJ3eL.js:9:90503)
    at Kb (https://railmapgen.github.io/rmp/assets/index-UvyvJ3eL.js:9:166701)
    at Zm (https://railmapgen.github.io/rmp/assets/react-hBmrxY6U.js:25:142550)
    at Hh (https://railmapgen.github.io/rmp/assets/react-hBmrxY6U.js:33:2780)

**Comment by thekingofcity** [comment]
嗨，方便上传設定檔到这里吗？

**Comment by GaHong3400** [comment]
> 嗨，方便上传設定檔到这里吗？


[RMP_1708267845159.json](https://github.com/railmapgen/rmp/files/14329209/RMP_1708267845159.json)

**Comment by thekingofcity** [comment]
嗨，已将您設定檔中的问题修复并上载到这里：

[RMP_1708267845159.json](https://github.com/railmapgen/rmp/files/14331291/RMP_1708267845159.json)

**Comment by GaHong3400** [comment]
> 嗨，已将您設定檔中的问题修复并上载到这里：
> 
> [RMP_1708267845159.json](https://github.com/railmapgen/rmp/files/14331291/RMP_1708267845159.json)

謝謝你！

**Comment by langonginc** [comment]
感谢您汇报这个问题，我们已经将它修复在 3.5.19 中修复～
